### ISSUE TITLE
Plugin exception error (Windows 7 only?)

### ISSUE THREAD

**Issue by Cariboudjan** [socks-the-fox/Chameleon#14]
![9E19F192-7085-43EA-BBFA-D5C744E7630B](https://user-images.githubusercontent.com/75376803/126016112-b49ebc86-62b1-45d2-94fe-1268904f083e.png)
![E095B679-845B-4ABC-BE13-68C46080C0A6](https://user-images.githubusercontent.com/75376803/126016120-97a64dfe-ec08-4a99-b23b-4084a53f8c67.png)

Users reporting this issue. ~~Seems to only affect Windows 7 but cannot verify. Works fine in Windows 10 as far as I am aware.~~

Edit:

~~Also affecting Windows 10 users, and seems to exclusively affect non-english speaking users with a non-english version of Windows 10 installed. Maybe this is caused by the way the plugin was encoded?~~

Edit:

Affects Windows 7 and 10, english and non-english versions of Windows.

**Comment by lucknaumann** [comment]
It also affects Windows 10 English version. I'm using Win10 20H2.

I have attached the log file with debugging turned on. If I hit Ignore a bunch of times, RM eventually loads. If I hit Retry, it quits.

[Rainmeter-Copy.log](https://github.com/socks-the-fox/Chameleon/files/6889778/Rainmeter-Copy.log)

**Comment by socks-the-fox** [comment]
What resolution is the image file you're trying to read? I have a feeling the issue is related to my attempt to scale the image before sampling the colors but getting some details on what could be causing this would help narrow it down, especially since I haven't run into this with my admittedly simplistic default skin.

**Comment by lucknaumann** [comment]
@socks-the-fox I'm not sure who you're addressing or if you're addressing both of us, but my wallpaper is 1920x1080p.

**Comment by socks-the-fox** [comment]
That's really odd, since there's really nothing unusual about that resolution. The only other thing I can think of is something in the skin that I forgot to account for (it wouldn't be the first time).

I've got a trip coming up soon with a few things I need to handle before that, but any info on anything even remotely relevant to image size or cropping in your skin might help me narrow it down and maybe get it fixed before then. Bonus points if you can create a minimal skin that causes the issue consistently!

**Comment by lucknaumann** [comment]
I'll look into the skins I use and see if I can find something. Sadly, I don't think I'm going to earn those bonus points, though. Did the log file I posted not help at all?

Have fun on your trip!

**Comment by socks-the-fox** [comment]
I did look and didn't really see anything, but there is a slim possibility that having 3 copies of Chameleon off the same file in the same skin might have something to do with it? I don't know why it would but I also know I didn't think to test that.

**Comment by lucknaumann** [comment]
I can't find 3 copies, but there are a lot of folders and files in that skin, Droptop: [DeviantArt](https://www.deviantart.com/cariboudjan/art/droptop-four-762812007) & [Website](https://blacksquare88.wixsite.com/droptop4/download).

It occurred to me that maybe the skin needed updating, and it did have an update. After updating, I didn't get any error messages, so maybe it's fixed (for that skin, anyway).

**Comment by Cariboudjan** [comment]
I have not experienced this error myself otherwise I would try to give more insight. 

My suite forces "~ HIGHDPIAWARE" binary key into registry to stop blurry skins. Could this setting in combination with a standard (100%) DPI cause this issue? I can't think of anything else.

**Comment by socks-the-fox** [comment]
It shouldn't cause the issue since Chameleon doesn't handle DPI in any way. It just loads the image (or snapshots the desktop background window, but the logfile above showed it directly reading an image) to RGB data, scales it down so it doesn't run the algorithm on really large images (this is the part that is currently breaking) and then samples the colors from the rescaled image.

**Comment by Cariboudjan** [comment]
@socks-the-fox 

One user of Droptop seems to have stopped the issue by changing the value of the variable that was responsible for cropping the wallpaper image from a formula to a constant.

eg. from

CropHeight=((#SCREENAREAHEIGHT#/1080)-((#SCREENAREAHEIGHT#/1080)%1))

to

CropHeight=26

`[ChameleonDesktopA]
Measure=Plugin
Plugin=Chameleon
Type=Desktop
CropX=0
CropY=0
CropW=(#WORKAREAWIDTH#/3)
CropH=#CropHeight#
ContextAwareColors=0
Group=Chameleon`

In either case both options have still not produced an error on my end, but this might help lead you to an answer. This has been reported by a single user only.

**Comment by socks-the-fox** [comment]
Interesting... that definitely narrows down where I might need to look, especially if I made a mistake with handling non-constant inputs.

**Comment by Cariboudjan** [comment]
I believe so, yes. I still cannot verify whether or not the change resulted in a fix as I can't personally replicate it. Pretty maddening.

**Comment by socks-the-fox** [comment]
I figured it out! Turns out it will throw the error only when CropW or CropH ends up being 0, whether due to an invalid input or just being set to 0. I didn't catch it because Chameleon passed my tests with negative values, and I never thought to test 0 separately. I'll be adding a check to see if either of those gets set to 0 and just use the last generated color if so.
